name: flutter_demo02
description: "本地测试项目"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.2+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_inappwebview: ^6.2.0-beta.2
  permission_handler: ^11.3.1
  flutter_downloader: ^1.11.8
  get: ^4.6.6
  fancy_bottom_navigation: ^0.3.3
  tdesign_flutter: ^0.1.7
  #  flutter_blue: 0.8.0
  flutter_blue_plus: ^1.34.5
  device_info_plus: ^11.2.0
  mobile_scanner: 6.0.2 # 废弃
  qr_code_scanner_plus: 2.0.6
  geolocator: 13.0.2
  flutter_local_notifications: 18.0.1
  #  image_picker: 1.1.2
  #  wechat_assets_picker: ^9.4.2
  #  image_picker: 1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/img/
    - assets/html/
    - assets/web-dist/
    - icons/

## 启用 mirrors
#dart:
#  vm:
#    product: false
#    experimental_features:
#      - mirrors

scripts:
  run: flutter run
  clean: flutter clean
  build_apk: flutter build apk --release
  build_ios: flutter build ios --release
  flutter_doctor: flutter doctor